### ISSUE TITLE
Display pi usage correct???

### ISSUE THREAD

**Issue by davidrobertwhite** [RossBarnie/rmt#1]
> > > lxc_base.pi_info() 
> > > {'ram_used': 76028L, 'cpu_usage': 100.0, 'ram_total': 188376L}

Doesn't look like it's reporting CPU usage correctly.

**Comment by RossBarnie** [comment]
This was listed as a bug in psutil (https://psutil.googlecode.com/hg/HISTORY) for OS X but was apparently fixed... Looking at the issue history of psutil, the issue seemed to almost resolve itself (http://code.google.com/p/psutil/issues/detail?id=120)

Additionally, the commands that the developers used to test cpu_percent() is:

> python -c 'import time,psutil; time.sleep(5); print psutil.cpu_percent(); time.sleep(5); print psutil.cpu_percent()'

which should return a value similar to "top" for example. Unfortunately for me it always returns 100 so it's either a problem with psutil, or the way I'm using it.

EDIT:
Looking at the output of "top", the CPU is actually always at 100% usage (or near enough).

```
%Cpu(s): 47.3 us, 52.4 sy...
```

Think this is something that won't ever be fixed since "top" itself is quite resource-heavy so could realistically be using all 700MHz of CPU.
